services:
  database:
    container_name: database
    image: "postgres:15.15"
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./hosting/data/db/:/var/lib/postgresql/data/
  storage:
    container_name: storage
    image: "rustfs/rustfs:1.0.0-alpha.78"
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      RUSTFS_ADDRESS: 9000
      RUSTFS_ACCESS_KEY: "${MINIO_ROOT_USER}"
      RUSTFS_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./hosting/data/storage/data:/data
      - ./hosting/data/storage/logs:/logs